sudo: true

services:
  - docker

script:
  - while sleep 8m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - docker build -t mikubill/docker-wrf:travis_build_$TRAVIS_BUILD_NUMBER .
  - docker login -u $docker_user -p $docker_token
  - docker push mikubill/docker-wrf:travis_build_$TRAVIS_BUILD_NUMBER
  - kill %1
