  
version: 2.1
      
commands:
  build-docker-image:
    steps:
      - run:
          name: Build Latest Docker Image
          command: |
            docker build -t mikubill/docker-wrf:circle_build_$CIRCLE_BUILD_NUM .
            # mv Dockerfile.d Dockerfile
            # docker build -t mikubill/docker-wrf:circle_build_$CIRCLE_BUILD_NUM_geog .
            docker login -u $docker_user -p $docker_token
            docker push mikubill/docker-wrf:circle_build_$CIRCLE_BUILD_NUM
            # docker push mikubill/docker-wrf:circle_build_$CIRCLE_BUILD_NUM_geog
          no_output_timeout: 1.5h


jobs:
  build:
    machine: true 
    steps:
      - restore_cache:
          keys: dep
      - checkout
      - build-docker-image
      - save_cache:
          key: dep
          paths:
            - "/var/lib/docker/"
